CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId VARCHAR(255) NOT NULL UNIQUE,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    blocked BOOLEAN,
    role ENUM('SUPERADMIN', 'ADMIN', 'AGENT', 'PLAYER') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
