CREATE TABLE bets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    matchId INT NOT NULL,
    playerId INT NOT NULL,
    betAmount INT NOT NULL,
    betSide VARCHAR(255) NOT NULL,
    win BOOLEAN NOT NULL,
    FOREIGN KEY (matchId) REFERENCES matches(id) ON DELETE CASCADE,
    FOREIGN KEY (playerId) REFERENCES players(id) ON DELETE CASCADE
);
