name: "Documentation Update"
description: "Propose changes or updates to the documentation"
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        **Propose updates or improvements to the documentation.**

  - type: input
    id: summary
    attributes:
      label: "Update Summary"
      description: "What part of the documentation needs updating?"
      placeholder: "Update Summary"

  - type: textarea
    id: current_status
    attributes:
      label: "Current Status"
      description: "What is currently missing, outdated, or unclear?"
      placeholder: "Describe the current state."

  - type: textarea
    id: proposed_changes
    attributes:
      label: "Proposed Changes"
      description: "Detail the changes you want to make."
      placeholder: "Describe proposed changes."

  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: "Add any relevant details."
      placeholder: "Provide additional context."
