// noinspection SpellCheckingInspection

export const GAME_TYPES = {
  ANDAR_BAHAR_TWO: "ANDAR_BAHAR_TWO",
  LUCKY7B: "LUCKY7B",
  TEEN_PATTI: "TEEN_PATTI",
  DRAGON_TIGER: "DRAGON_TIGER",
  ANDAR_BAHAR: "ANDAR_BAHAR",
  DRAGON_TIGER_LION: "DRAGON_TIGER_LION",
};

export const GAME_STATES = {
  WAITING: "waiting",
  BETTING: "betting",
  DEALING: "dealing",
  COMPLETED: "completed",
};

export const GAME_CONFIGS = [
  {
    id: "AB2",
    type: GAME_TYPES.ANDAR_BAHAR_TWO,
    name: "Andar Bahar 2",
    betOptions: ["andar", "bahar"],
    multipiers: { andar: 1.95, bahar: 1.95 },
    dealingDuration: 5000,
    bettingDuration: 20000,
    bettingDuration: 20000,
    joker: true,
    blind: true,
  },

  {
    id: "L7B",
    type: GAME_TYPES.LUCKY7B,
    name: "Lucky 7B",
    betOptions: ["low", "high", "mid", "even", "odd", "black", "red"],
    multipliers: {
      low: 1.8,
      high: 1.8,
      mid: 8,
      even: 1.8,
      odd: 1.8,
      black: 1.8,
      red: 1.8,
    },
    dealingDuration: 3000,
    bettingDuration: 20000,
    cardDealInterval: 500,
    joker: false,
    blind: true,
  },
  {
    id: "TP1",
    type: GAME_TYPES.TEEN_PATTI,
    name: "Teen Patti T20",
    betOptions: ["playerA", "playerB"],
    multipliers: { default: 1.9 },
    dealingDuration: 5000,
    bettingDuration: 30000,
    cardDealInterval: 1000,
    cardsPerPlayer: 3,
    joker: false,
    blind: true,
  },
  {
    id: "DT20",
    type: GAME_TYPES.DRAGON_TIGER,
    name: "Dragon Tiger 20-20",
    betOptions: [
      "dragon",
      "tiger",
      "tie",
      "pair",
      "odd",
      "even",
      "black",
      "red",
      "specificCard",
    ],
    multipliers: {
      dragon: 1.98,
      tiger: 1.98,
      tie: 11,
      pair: 12,
      odd: 1.8,
      even: 1.8,
      black: 1.8,
      red: 1.8,
      specificCard: 8,
    },
    dealingDuration: 3000,
    bettingDuration: 20000,
    cardDealInterval: 500,
    blind: true,
  },
  {
    id: "AB1",
    type: GAME_TYPES.ANDAR_BAHAR,
    name: "Andar Bahar 1",
    betOptions: ["andar", "bahar"],
    multipliers: { default: 1.95 },
    dealingDuration: 5000,
    bettingDuration: 20000,
    cardDealInterval: 1000,
    joker: true,
    blind: true,
  },
  {
    id: "DTL20",
    type: GAME_TYPES.DRAGON_TIGER_LION,
    name: "Dragon Tiger Lion 20-20",
    betOptions: ["dragon", "tiger", "lion", "black", "red", "odd", "even"],
    multipliers: {
      dragon: 1.98,
      tiger: 1.98,
      lion: 1.98,
      black: 1.8,
      red: 1.8,
      odd: 1.8,
      even: 1.8,
    },
    dealingDuration: 5000,
    bettingDuration: 20000,
    cardDealInterval: 500,
    joker: false,
    blind: true,
  },
];
